# Use the official Python image
FROM python:3.10-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy the Python script
COPY shamir.py .

# Define the entrypoint command
ENTRYPOINT ["python3", "shamir.py"]